=== Kilian565/GurpsSheet-XML/gurpsSCHEMA.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://tempuri.org/XMLSchema.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/XMLSchema.xsd"
    xmlns:mstns="http://tempuri.org/XMLSchema.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:complexType name="charblaetter">
    <xs:sequence>
      <xs:element ref="charakter" maxOccurs="unbounded" minOccurs="0"></xs:element>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="charbogen">
    <xs:sequence>
      <xs:element ref="spieler"></xs:element>
      <xs:element ref="attribute"></xs:element>
      <xs:element ref="inventar"></xs:element>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:int" use="required"></xs:attribute>


  </xs:complexType>

  <xs:complexType name="spielerinfos">
    <xs:sequence>
      <xs:element ref="spielername"></xs:element>
      <xs:element ref="charname"></xs:element>
      <xs:element ref="charstory"></xs:element>
      <xs:element ref="gebjahr"></xs:element>
      <xs:element ref="reihenfolge"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name ="attribute">
    <xs:sequence>
      <xs:element ref="stats"></xs:element>
      <xs:element ref="bewegung"></xs:element>
      <xs:element ref="schaden"></xs:element>
      <xs:element ref="faehigkeiten"></xs:element>
      <xs:element ref="vorteile"></xs:element>
      <xs:element ref="nachteile"></xs:element>
      <xs:element ref="marotten"></xs:element>
    </xs:sequence>

  </xs:complexType>

  <xs:complexType name="stats">
    <xs:sequence>
      <xs:element ref="cpgesamt"></xs:element>
      <xs:element ref="staerke"></xs:element>
      <xs:element ref="geschicklichkeit"></xs:element>
      <xs:element ref="intelligenz"></xs:element>
      <xs:element ref="konstitution"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="bewegung">
    <xs:sequence>
      <xs:element ref="grundgeschwindigkeit"></xs:element>
      <xs:element ref="belastungswert"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="schaden">
    <xs:sequence>
      <xs:element ref="schwungschaden"></xs:element>
      <xs:element ref="stossschaden"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="faehigkeiten">
    <xs:sequence>
      <xs:element ref="physischefaehigkeiten"></xs:element>
      <xs:element ref="mentalefaehigkeiten"></xs:element>
    </xs:sequence>

  </xs:complexType>
  <xs:complexType name="mentalefaehigkeiten">
    <xs:sequence>

      <xs:element ref="fertigkeit"></xs:element>

    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="physischefaehigkeiten">
    <xs:sequence>

      <xs:element ref="fertigkeit"></xs:element>

    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="fertigkeit">
    <xs:sequence>
      <xs:element ref="beschreibung"></xs:element>
      <xs:element ref="wert"></xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="vorteile">
    <xs:sequence>
      <xs:element ref="cp"></xs:element>
      <xs:element ref="beschreibung"></xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="nachteile">
    <xs:sequence>
      <xs:element ref="cp"></xs:element>
      <xs:element ref="beschreibung"></xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="marotten">
    <xs:sequence>
      <xs:element ref="cp"></xs:element>
      <xs:element ref="beschreibung"></xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="inventar">
    <xs:sequence>
      <xs:element ref="gegenstand" maxOccurs="unbounded" minOccurs="0" ></xs:element>
    </xs:sequence>

  </xs:complexType>


  <xs:complexType name="itemstats">

    <xs:all>
      <xs:element ref="fertigkeitswert"></xs:element>
      <xs:element ref="schadenstyp"></xs:element>
      <xs:element ref="schadenshoehe"></xs:element>
      <xs:element ref="reichweite"></xs:element>
    </xs:all>



  </xs:complexType>

  <xs:complexType name="gegenstand">
    <xs:sequence>
      <xs:element ref="preis"></xs:element>
      <xs:element ref="gewicht"></xs:element>
      <xs:element ref="anzahl"></xs:element>
      <xs:element ref="itemstats"></xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
  </xs:complexType>



  <xs:element name="gurps" type="charblaetter"></xs:element>
  <xs:element name="charakter" type="charbogen"></xs:element>
  <xs:element name="attribute" type="attribute"></xs:element>

  <xs:element name="spieler" type="spielerinfos" ></xs:element>
  <xs:element name="spielername" type="xs:string"></xs:element>
  <xs:element name="charname" type="xs:string"></xs:element>
  <xs:element name="charstory" type="xs:string"></xs:element>
  <xs:element name="gebjahr" type="xs:int"></xs:element>
  <xs:element name="reihenfolge" type="xs:int" ></xs:element>

  <xs:element name="stats" type="stats"></xs:element>
  <xs:element name="cpgesamt" type="xs:int" default="0"></xs:element>
  <xs:element name="staerke" type="xs:int" default="0"></xs:element>
  <xs:element name="geschicklichkeit" type="xs:int" default="0"></xs:element>
  <xs:element name="intelligenz" type="xs:int" default="0"></xs:element>
  <xs:element name="konstitution" type="xs:int" default="0"></xs:element>
  <xs:element name="bewegung" type="bewegung"></xs:element>
  <xs:element name="grundgeschwindigkeit" type="xs:int" default="0"></xs:element>
  <xs:element name="belastungswert" type="xs:int"></xs:element>

  <xs:element name="schaden" type="schaden"></xs:element>
  <xs:element name="schwungschaden" type="xs:int" default="0"></xs:element>
  <xs:element name="stossschaden" type="xs:int" default="0"></xs:element>

  <xs:element name="faehigkeiten" type="faehigkeiten"></xs:element>
  <xs:element name="mentalefaehigkeiten" type="mentalefaehigkeiten"></xs:element>
  <xs:element name="physischefaehigkeiten" type="physischefaehigkeiten"></xs:element>
  <xs:element name="fertigkeit" type="fertigkeit"></xs:element>


  <xs:element name="beschreibung" type="xs:string"></xs:element>
  <xs:element name="wert" type="xs:int" default="0"></xs:element>

  <xs:element name="vorteile" type="vorteile"></xs:element>
  <xs:element name="nachteile" type="nachteile"></xs:element>
  <xs:element name="marotten" type="marotten"></xs:element>
  <xs:element name="name" type="xs:string"></xs:element>
  <xs:element name="cp" type="xs:int" default="0"></xs:element>

  <xs:element name="inventar" type="inventar"></xs:element>
  <xs:element name="gegenstand" type="gegenstand"></xs:element>
  <xs:element name="preis" type="xs:int" default="1"></xs:element>
  <xs:element name="gewicht" type="xs:int" default="0"></xs:element>
  <xs:element name="anzahl" type="xs:int" default="0"></xs:element>
  <xs:element name="itemstats" type="itemstats"></xs:element>
  <xs:element name="fertigkeitswert" type="xs:int" default="0"></xs:element>
  <xs:element name="schadenstyp" type="xs:string" default="0"></xs:element>
  <xs:element name="schadenshoehe" type="xs:int" default="0"></xs:element>
  <xs:element name="reichweite" type="xs:int" default="0"></xs:element>





</xs:schema>

=== Kilian565/GurpsSheet-XML/gurpsXML(nicht für XSLT).xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="xslt.xslt"  type="text/xsl" ?>


<gurps xmlns="http://tempuri.org/XMLSchema.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://tempuri.org/XMLSchema.xsd C:\Users\homeuser\Desktop\XML\gurpsSCHEMA.xsd">
  <charakter ID="1">
    <spieler>
      <spielername>spielername1</spielername>
      <charname>charname1</charname>
      <charstory>charstory1</charstory>
      <gebjahr>1</gebjahr>
      <reihenfolge>1</reihenfolge>
    </spieler>
    <attribute>
      <stats>
        <cpgesamt>0</cpgesamt>
        <staerke>0</staerke>
        <geschicklichkeit>0</geschicklichkeit>
        <intelligenz>0</intelligenz>
        <konstitution>0</konstitution>
      </stats>
      <bewegung>
        <grundgeschwindigkeit>0</grundgeschwindigkeit>
        <belastungswert>1</belastungswert>
      </bewegung>
      <schaden>
        <schwungschaden>0</schwungschaden>
        <stossschaden>0</stossschaden>
      </schaden>
      <faehigkeiten>
        <physischefaehigkeiten>
          <fertigkeit name="name1">
            <beschreibung>beschreibung1</beschreibung>
            <wert>0</wert>
          </fertigkeit>
        </physischefaehigkeiten>
        <mentalefaehigkeiten>
          <fertigkeit name="name2">
            <beschreibung>beschreibung2</beschreibung>
            <wert>1</wert>
          </fertigkeit>
        </mentalefaehigkeiten>
      </faehigkeiten>
      <vorteile name="name1">
        <cp>0</cp>
        <beschreibung>beschreibung1</beschreibung>
      </vorteile>
      <nachteile name="name1">
        <cp>0</cp>
        <beschreibung>beschreibung1</beschreibung>
      </nachteile>
      <marotten name="name1">
        <cp>0</cp>
        <beschreibung>beschreibung1</beschreibung>
      </marotten>
    </attribute>
    <inventar>
      <gegenstand name="name1">
        <preis>1</preis>
        <gewicht>0</gewicht>
        <anzahl>0</anzahl>
        <itemstats>
          <reichweite>0</reichweite>
          <schadenshoehe>0</schadenshoehe>
          <schadenstyp>0</schadenstyp>
          <fertigkeitswert>0</fertigkeitswert>
        </itemstats>
      </gegenstand>
      <gegenstand name="name2">
        <preis>1</preis>
        <gewicht>1</gewicht>
        <anzahl>1</anzahl>
        <itemstats>
          <reichweite>1</reichweite>
          <schadenshoehe>1</schadenshoehe>
          <schadenstyp>schadenstyp1</schadenstyp>
          <fertigkeitswert>1</fertigkeitswert>
        </itemstats>
      </gegenstand>
      <gegenstand name="name3">
        <preis>-2147483647</preis>
        <gewicht>-2147483647</gewicht>
        <anzahl>-2147483647</anzahl>
        <itemstats>
          <reichweite>-2147483647</reichweite>
          <schadenshoehe>-2147483647</schadenshoehe>
          <schadenstyp>schadenstyp2</schadenstyp>
          <fertigkeitswert>-2147483647</fertigkeitswert>
        </itemstats>
      </gegenstand>
    </inventar>
  </charakter>
  <charakter ID="-2147483647">
    <spieler>
      <spielername>spielername2</spielername>
      <charname>charname2</charname>
      <charstory>charstory2</charstory>
      <gebjahr>-2147483647</gebjahr>
      <reihenfolge>-2147483647</reihenfolge>
    </spieler>
    <attribute>
      <stats>
        <cpgesamt>1</cpgesamt>
        <staerke>1</staerke>
        <geschicklichkeit>1</geschicklichkeit>
        <intelligenz>1</intelligenz>
      </stats>
      <bewegung>
        <grundgeschwindigkeit>1</grundgeschwindigkeit>
        <belastungswert>-2147483647</belastungswert>
      </bewegung>
      <schaden>
        <schwungschaden>1</schwungschaden>
        <stossschaden>1</stossschaden>
      </schaden>
      <faehigkeiten>
        <physischefaehigkeiten>
          <fertigkeit name="name3">
            <beschreibung>beschreibung3</beschreibung>
            <wert>-2147483647</wert>
          </fertigkeit>
        </physischefaehigkeiten>
        <mentalefaehigkeiten>
          <fertigkeit name="name4">
            <beschreibung>beschreibung4</beschreibung>
            <wert>2147483647</wert>
          </fertigkeit>
        </mentalefaehigkeiten>
      </faehigkeiten>
      <vorteile name="name2">
        <cp>1</cp>
        <beschreibung>beschreibung2</beschreibung>
      </vorteile>
      <nachteile name="name2">
        <cp>1</cp>
        <beschreibung>beschreibung2</beschreibung>
      </nachteile>
      <marotten name="name2">
        <cp>1</cp>
        <beschreibung>beschreibung2</beschreibung>
      </marotten>
    </attribute>
    <inventar>
      <gegenstand name="name4">
        <preis>2147483647</preis>
        <gewicht>2147483647</gewicht>
        <anzahl>2147483647</anzahl>
        <itemstats>
          <reichweite>2147483647</reichweite>
          <schadenshoehe>2147483647</schadenshoehe>
          <schadenstyp>schadenstyp3</schadenstyp>
          <fertigkeitswert>2147483647</fertigkeitswert>
        </itemstats>
      </gegenstand>
      <gegenstand name="name5">
        <preis>0</preis>
        <gewicht>0</gewicht>
        <anzahl>0</anzahl>
        <itemstats>
          <reichweite>0</reichweite>
          <schadenshoehe>0</schadenshoehe>
          <schadenstyp>schadenstyp4</schadenstyp>
          <fertigkeitswert>0</fertigkeitswert>
        </itemstats>
      </gegenstand>
      <gegenstand name="name6">
        <preis>2</preis>
        <gewicht>2</gewicht>
        <anzahl>2</anzahl>
        <itemstats>
          <reichweite>2</reichweite>
          <schadenshoehe>2</schadenshoehe>
          <schadenstyp>schadenstyp5</schadenstyp>
          <fertigkeitswert>2</fertigkeitswert>
        </itemstats>
      </gegenstand>
    </inventar>
  </charakter>
  <charakter ID="2147483647">
    <spieler>
      <spielername>spielername3</spielername>
      <charname>charname3</charname>
      <charstory>charstory3</charstory>
      <gebjahr>2147483647</gebjahr>
      <reihenfolge>2147483647</reihenfolge>
    </spieler>
    <attribute>
      <stats>
        <cpgesamt>-2147483647</cpgesamt>
        <staerke>-2147483647</staerke>
        <geschicklichkeit>-2147483647</geschicklichkeit>
        <intelligenz>-2147483647</intelligenz>
      </stats>
      <bewegung>
        <grundgeschwindigkeit>-2147483647</grundgeschwindigkeit>
        <belastungswert>2147483647</belastungswert>
      </bewegung>
      <schaden>
        <schwungschaden>-2147483647</schwungschaden>
        <stossschaden>-2147483647</stossschaden>
      </schaden>
      <faehigkeiten>
        <physischefaehigkeiten>
          <fertigkeit name="name5">
            <beschreibung>beschreibung5</beschreibung>
            <wert>0</wert>
          </fertigkeit>
        </physischefaehigkeiten>
        <mentalefaehigkeiten>
          <fertigkeit name="name6">
            <beschreibung>beschreibung6</beschreibung>
            <wert>2</wert>
          </fertigkeit>
        </mentalefaehigkeiten>
      </faehigkeiten>
      <vorteile name="name3">
        <cp>-2147483647</cp>
        <beschreibung>beschreibung3</beschreibung>
      </vorteile>
      <nachteile name="name3">
        <cp>-2147483647</cp>
        <beschreibung>beschreibung3</beschreibung>
      </nachteile>
      <marotten name="name3">
        <cp>-2147483647</cp>
        <beschreibung>beschreibung3</beschreibung>
      </marotten>
    </attribute>
    <inventar>
      <gegenstand name="name7">
        <preis>-2147483646</preis>
        <gewicht>-2147483646</gewicht>
        <anzahl>-2147483646</anzahl>
        <itemstats>
          <reichweite>-2147483646</reichweite>
          <schadenshoehe>-2147483646</schadenshoehe>
          <schadenstyp>schadenstyp6</schadenstyp>
          <fertigkeitswert>-2147483646</fertigkeitswert>
        </itemstats>
      </gegenstand>
      <gegenstand name="name8">
        <preis>2147483646</preis>
        <gewicht>2147483646</gewicht>
        <anzahl>2147483646</anzahl>
        <itemstats>
          <reichweite>2147483646</reichweite>
          <schadenshoehe>2147483646</schadenshoehe>
          <schadenstyp>schadenstyp7</schadenstyp>
          <fertigkeitswert>2147483646</fertigkeitswert>
        </itemstats>
      </gegenstand>
      <gegenstand name="name9">
        <preis>-1</preis>
        <gewicht>-1</gewicht>
        <anzahl>-1</anzahl>
        <itemstats>
          <reichweite>-1</reichweite>
          <schadenshoehe>-1</schadenshoehe>
          <schadenstyp>schadenstyp8</schadenstyp>
          <fertigkeitswert>-1</fertigkeitswert>
        </itemstats>
      </gegenstand>
    </inventar>
  </charakter>
</gurps>
